root = "/data"
tmp_dir = "tmp"

[build]
  bin = "./tmp/goadmin-api -f /data/yaml/goadmin-api.yaml"
  cmd = "go build -o ./tmp/goadmin-api /data/api/goadmin.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html","yaml"]
  kill_delay = "0s"
  log = "log/build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
